### ISSUE TITLE
Broken in new Rails 5 project

### ISSUE THREAD

**Issue by NullVoxPopuli** [madzhuga/rails_workflow#21]
```
$  rails generate rails_workflow:install
/home/me/.rvm/gems/ruby-2.3.1/gems/draper-2.1.0/lib/draper.rb:5:in `require': cannot load such file -- active_model/serializers/xml (LoadError)
	from /home/me/.rvm/gems/ruby-2.3.1/gems/draper-2.1.0/lib/draper.rb:5:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/rails_workflow-0.3.6/lib/rails_workflow.rb:7:in `require'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/rails_workflow-0.3.6/lib/rails_workflow.rb:7:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from /home/me/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
	from /home/me/Downloads/rails_workflow_test/config/application.rb:7:in `<top (required)>'
```

**Comment by madzhuga** [comment]
@NullVoxPopuli it's not rails_workflow bug. Please check [this thread](https://github.com/drapergem/draper/issues/697).

**Comment by NullVoxPopuli** [comment]
by having this in my gemfile, everything works:

```ruby
gem 'rails_workflow'
gem 'activemodel-serializers-xml', github: 'rails/activemodel-serializers-xml'
gem 'draper', github: 'audionerd/draper', branch: 'rails5'
gem 'responders', github: 'plataformatec/responders'
```
