### ISSUE TITLE
undefined method `role_text' for #<Class:0x007fd0e389f3a8>

### ISSUE THREAD

**Issue by rpbaltazar** [madzhuga/rails_workflow#25]
Trying to follow your wiki instructions, after filling up the form according to the wiki, I get this error thrown.

Does this gem assume anything about User roles availability?

![screen shot 2017-02-20 at 12 17 02 pm](https://cloud.githubusercontent.com/assets/5548466/23111879/8628ef70-f766-11e6-9bc1-fd7217798992.png)

**Comment by madzhuga** [comment]
Hi @rpbaltazar! :) Can you please provide full stack trace?

**Comment by rpbaltazar** [comment]
```
Showing /Users/neo/.rvm/gems/ruby-2.3.1@airdrilling/gems/rails_workflow-0.3.7/app/views/rails_workflow/operation_templates/index.html.slim where line #40 raised:

undefined method `role_text' for #<Class:0x007fd0e6f851b0>

activerecord (4.2.0) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
rails_workflow (0.3.7) app/decorators/rails_workflow/operation_template_decorator.rb:45:in `assignment'
rails_workflow (0.3.7) app/views/rails_workflow/operation_templates/index.html.slim:40:in `block in ___sers_neo__rvm_gems_ruby_______airdrilling_gems_rails_workflow_______app_views_rails_workflow_operation_templates_index_html_slim__2005467902801794232_70267351654100'
draper (2.1.0) lib/draper/delegation.rb:10:in `each'
draper (2.1.0) lib/draper/delegation.rb:10:in `each'
rails_workflow (0.3.7) app/views/rails_workflow/operation_templates/index.html.slim:37:in `___sers_neo__rvm_gems_ruby_______airdrilling_gems_rails_workflow_______app_views_rails_workflow_operation_templates_index_html_slim__2005467902801794232_70267351654100'
actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.0) lib/action_view/template.rb:143:in `render'
haml_coffee_assets (1.16.0) lib/haml_coffee_assets/rails/engine.rb:73:in `render'
actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/neo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
remotipart (1.3.1) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.5.0) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.5.0) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
railties (4.2.0) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
newrelic_rpm (3.18.1.330) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/deflater.rb:35:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.0) lib/thin/connection.rb:84:in `catch'
thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.0) lib/thin/connection.rb:53:in `process'
thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.2) lib/eventmachine.rb:194:in `run_machine'
eventmachine (1.2.2) lib/eventmachine.rb:194:in `run'
thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
thin (1.7.0) lib/thin/server.rb:162:in `start'
rack (1.6.5) lib/rack/handler/thin.rb:19:in `run'
rack (1.6.5) lib/rack/server.rb:286:in `start'
railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `tap'
railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:25:in `require'
bin/rails:25:in `<top (required)>'
spring (2.0.1) lib/spring/client/rails.rb:28:in `load'
spring (2.0.1) lib/spring/client/rails.rb:28:in `call'
spring (2.0.1) lib/spring/client/command.rb:7:in `call'
spring (2.0.1) lib/spring/client.rb:30:in `run'
spring (2.0.1) bin/spring:49:in `<top (required)>'
spring (2.0.1) lib/spring/binstub.rb:31:in `load'
spring (2.0.1) lib/spring/binstub.rb:31:in `<top (required)>'
bin/spring:16:in `require'
bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

**Comment by madzhuga** [comment]
@rpbaltazar thanks! It looks like a bug - this decorator should not use user roles in any way. I will check that today.

**Comment by madzhuga** [comment]
@rpbaltazar it actually failed not on a screenshot page but it actually failed from operation templates index page. There it lists operation templates and their assignments (since there can be User operations). User operations going to be assigned to users by groups or roles. Please check `app/concerns/rails_workflow/user/assignment.rb` and also check `spec/dummy/app/models/user.rb` - it will give you better understanding of what this is about. :) Feel free to ask any questions.

**Comment by madzhuga** [comment]
@rpbaltazar I am closing this issue. Let me know if you have some other questions.
