### ISSUE TITLE
Rails 5.1 Incompatibility

### ISSUE THREAD

**Issue by edave** [madzhuga/rails_workflow#36]
Processing fails on Rails 5.1 due to this error:
```ruby
wrong number of arguments (given 1, expected 0)
/Users/dpitman/.rvm/gems/ruby-2.3.5/gems/activerecord-5.1.4/lib/active_record/associations/collection_association.rb:28:in `reader'
/Users/dpitman/.rvm/gems/ruby-2.3.5/gems/activerecord-5.1.4/lib/active_record/associations/builder/association.rb:111:in `operations'
/Users/dpitman/others-repositories/rails_workflow/app/models/rails_workflow/process.rb:50:in `uncompleted_operations'
/Users/dpitman/others-repositories/rails_workflow/app/models/rails_workflow/process.rb:44:in `uncompleted?'
```

This is fixed by not passing in `true` to the `operations` association in `RailsWorkflow::Process`:
https://github.com/converge-co/rails_workflow/commit/630a4c8e541c603e6049475ed168e8a284a23c6c

**Comment by madzhuga** [comment]
@edave thank you for reporting this bug. I will check and fix in nearest time.

**Comment by madzhuga** [comment]
Fixed in master.
