### ISSUE TITLE
Please support MySQL via mysql2 gem [feature request]

### ISSUE THREAD

**Issue by samnissen** [madzhuga/rails_workflow#5]
```bash
$ rails generate rails_workflow:install
$ bundle exec rake db:migrate
```
```ruby
== 20150630090558 CreateWorkflowProcesses: migrating ==========================
-- table_exists?(:workflow_processes)
   -> 0.0007s
-- table_exists?(:rails_workflow_processes)
   -> 0.0003s
-- table_exists?(:workflow_operations)
   -> 0.0005s
-- table_exists?(:rails_workflow_operations)
   -> 0.0003s
-- table_exists?(:workflow_process_templates)
   -> 0.0005s
-- table_exists?(:rails_workflow_process_templates)
   -> 0.0003s
-- table_exists?(:workflow_operation_templates)
   -> 0.0005s
-- table_exists?(:rails_workflow_operation_templates)
   -> 0.0003s
-- table_exists?(:workflow_contexts)
   -> 0.0005s
-- table_exists?(:rails_workflow_contexts)
   -> 0.0003s
-- table_exists?(:workflow_errors)
   -> 0.0005s
-- table_exists?(:rails_workflow_errors)
   -> 0.0003s
-- column_exists?(:rails_workflow_contexts, :parent_id)
   -> 0.0014s
-- column_exists?(:rails_workflow_contexts, :parent_type)
   -> 0.0009s
-- column_exists?(:rails_workflow_contexts, :body)
   -> 0.0010s
-- column_exists?(:rails_workflow_contexts, :created_at)
   -> 0.0009s
-- column_exists?(:rails_workflow_contexts, :updated_at)
   -> 0.0010s
-- column_exists?(:rails_workflow_errors, :message)
   -> 0.0011s
-- column_exists?(:rails_workflow_errors, :stack_trace)
   -> 0.0010s
-- column_exists?(:rails_workflow_errors, :parent_id)
   -> 0.0009s
-- column_exists?(:rails_workflow_errors, :parent_type)
   -> 0.0010s
-- column_exists?(:rails_workflow_errors, :created_at)
   -> 0.0010s
-- column_exists?(:rails_workflow_errors, :updated_at)
   -> 0.0010s
-- column_exists?(:rails_workflow_errors, :resolved)
   -> 0.0010s
-- column_exists?(:rails_workflow_operation_templates, :title)
   -> 0.0010s
-- column_exists?(:rails_workflow_operation_templates, :version)
   -> 0.0010s
-- column_exists?(:rails_workflow_operation_templates, :uuid)
   -> 0.0009s
-- add_column(:rails_workflow_operation_templates, :uuid, :uuid)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uuid' at line 1: ALTER TABLE `rails_workflow_operation_templates` ADD `uuid` uuid
# ...
/app/db/migrate/20150630090558_create_workflow_processes.rb:136:in `block (2 levels) in create_columns'
/app/db/migrate/20150630090558_create_workflow_processes.rb:134:in `map'
/app/db/migrate/20150630090558_create_workflow_processes.rb:134:in `block in create_columns'
/app/db/migrate/20150630090558_create_workflow_processes.rb:133:in `each'
/app/db/migrate/20150630090558_create_workflow_processes.rb:133:in `create_columns'
/app/db/migrate/20150630090558_create_workflow_processes.rb:4:in `change'
# ...
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uuid' at line 1: ALTER TABLE `rails_workflow_operation_templates` ADD `uuid` uuid
# ...
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uuid' at line 1
# ...
```

**Comment by madzhuga** [comment]
I will fix that today. Also it looks like I will have to add configuration setting to use mysql as it prevents me from using postgres-like window functions and some other stuff... I will add more information about it today.

**Comment by waleedjaffar** [comment]
Hi Samnissen,

You can modify migration file as:
1. Replace **[:uuid,     :uuid],** as **[char(36),     :uuid],** at line 66 and 111

and execute db:migrate

Regards,
Waleed

**Comment by samnissen** [comment]
Thanks @madzhuga If I knew more about Postgres, I would submit along with a PR ... but then I probably wouldn't be requesting MySQL support. :]

And thank you @waleedjaffar -- if I need to wedge this in before official support I'll follow your instructions.

**Comment by madzhuga** [comment]
@samnissen and @waleedjaffar try 0.3.2 version. I removed uuid and added mysql / pg separate dialects. Please make sure you have config/initializers/workflow.rb file:
```ruby
RailsWorkflow.setup do |config|
  config.sql_dialect= 'mysql'
end
```
to use mysql query instead of pg query with window functions

**Comment by samnissen** [comment]
Thank you for this!
